version: '3.8'

services:
  # Backend Server
  server:
    build: 
      context: ./server
      dockerfile: Dockerfile
    container_name: yellowai-server
    restart: unless-stopped
    ports:
      - "3001:3000"
    environment:
      NODE_ENV: production
      PORT: 3000
      MONGODB_URI: ${MONGODB_URI}
      JWT_SECRET: ${JWT_SECRET}
      JWT_REFRESH_SECRET: ${JWT_REFRESH_SECRET}
      SESSION_SECRET: ${SESSION_SECRET}
      GEMINI_API_KEY: ${GEMINI_API_KEY}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      CLIENT_URL: ${CLIENT_URL}
      SERVER_URL: ${SERVER_URL}
      ALLOWED_ORIGINS: ${ALLOWED_ORIGINS}
    volumes:
      - ./server/uploads:/app/uploads
    networks:
      - yellowai-network
    healthcheck:
      test: ["CMD", "node", "healthcheck.js"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Frontend Client
  client:
    build: 
      context: ./client
      dockerfile: Dockerfile
      args:
        VITE_SERVER_URL: http://3.108.221.6:3001
    container_name: yellowai-client
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      server:
        condition: service_healthy
    networks:
      - yellowai-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

volumes:

networks:
  yellowai-network:
    driver: bridge